http://localhost:3000/aluno

###

POST http://localhost:3000/aluno HTTP/1.1
content-type: application/json

{
    "nome": "José"
}

###

PUT http://localhost:3000/aluno/2 HTTP/1.1
content-type: application/json

{
    "nome": "José 22"
}

###

DELETE  http://localhost:3000/aluno/2
